### ISSUE TITLE
How do we start the dialogue?

### ISSUE THREAD

**Issue by jbdhibd** [ejnij/Godot-DialogGraphPlugin#4]
I am a noob at godot u see, is there a script to start the dialogue? It has already clearly been explained what the different nodes are but how do we start the dialogue? For instance, if a key is pressed, i want the dialogue to start.

**Comment by Boivin92** [comment]
the DialogManager node has a start_dialog() method that will start at the default dialogue. Optionally you may pass the name of a particular Dialogue you want to start as a parameter.

When you want to move to the next dialogue node, simply call continue_dialog() on the manager

**Comment by jbdhibd** [comment]
What about the graphics of the dialog? How do i set that?
